- name: Install Netdata on Backend
  hosts: backend
  become: yes
  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present
      when: ansible_os_family == "Debian"

    - name: Install curl
      yum:
        name: curl
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Netdata
      shell: |
        bash <(curl -Ss https://get.netdata.cloud/kickstart.sh) --dont-wait
      args:
        executable: /bin/bash

    - name: Ensure Netdata is running
      service:
        name: netdata
        state: started
        enabled: yes
      ignore_errors: yes
