- name: Install and configure Nginx on Frontend
  hosts: frontend
  become: yes
  vars:
    backend_ip: "{{ hostvars['backend1'].ansible_host }}"

  tasks:
    - name: Enable Nginx (for Amazon Linux 2)
      shell: amazon-linux-extras enable nginx1
      when: ansible_distribution == "Amazon"
      args:
        executable: /bin/bash

    - name: Install Nginx (Amazon/RedHat)
      yum:
        name: nginx
        state: present
      when: ansible_distribution in ["Amazon", "RedHat"]

    - name: Start & enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create Nginx proxy config for Netdata backend
      template:
        src: templates/netdata_proxy.conf.j2
        dest: /etc/nginx/conf.d/netdata_proxy.conf

    - name: Restart Nginx to apply config
      service:
        name: nginx
        state: restarted
