- name: Install and configure Nginx on Frontend
  hosts: frontend
  become: yes

  tasks:
    - name: Enable Nginx in amazon-linux-extras (for Amazon Linux 2)
      command: amazon-linux-extras enable nginx1
      when: ansible_distribution == "Amazon"

    - name: Install Nginx
      yum:
        name: nginx
        state: present
      when: ansible_distribution in ["Amazon", "RedHat"]

    - name: Deploy default index.html page
      copy:
        dest: /usr/share/nginx/html/index.html
        content: "<h1>Welcome to Frontend Nginx on Port 80</h1>"

    - name: Deploy Nginx reverse proxy config
      copy:
        src: netdata_proxy.conf
        dest: /etc/nginx/conf.d/netdata_proxy.conf
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
