- name: Install and configure Nginx on Frontend
  hosts: frontend
  become: yes

  tasks:
    - name: Install Nginx on Amazon Linux 2023
      ansible.builtin.shell: |
        microdnf install -y nginx
      when: ansible_distribution == "Amazon"
      args:
        executable: /bin/bash

    - name: Install Nginx on Debian/Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Deploy default index.html page
      copy:
        dest: /usr/share/nginx/html/index.html
        content: "<h1>Welcome to Frontend Nginx on Port 80</h1>"

    - name: Deploy Nginx reverse proxy config
      copy:
        src: netdata_proxy.conf
        dest: /etc/nginx/conf.d/netdata_proxy.conf
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
