- name: Install and configure Nginx
  hosts: frontend
  become: yes
  tasks:
    - name: Install Nginx on RedHat/Amazon Linux
      yum:
        name: nginx
        state: present
      when: ansible_os_family in ["RedHat", "Amazon"]

    - name: Install Nginx on Debian/Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
