- name: Install and configure Nginx on Frontend
  hosts: frontend
  become: yes

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Copy custom Nginx config to /etc/nginx/nginx.conf
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          events {
              worker_connections 1024;
          }

          http {
              include       mime.types;
              default_type  application/octet-stream;
              sendfile        on;
              keepalive_timeout  65;

              server {
                  listen 80;
                  server_name _;

                  root /usr/share/nginx/html;
                  index index.html index.htm;
              }

              upstream backend_netdata {
                  server 44.210.117.103:19999;
              }

              server {
                  listen 19999;
                  server_name _;

                  location / {
                      proxy_pass http://backend_netdata;
                      proxy_http_version 1.1;
                      proxy_set_header Upgrade $http_upgrade;
                      proxy_set_header Connection 'upgrade';
                      proxy_set_header Host $host;
                      proxy_cache_bypass $http_upgrade;
                  }
              }
          }

    - name: Restart Nginx to apply new config
      service:
        name: nginx
        state: restarted
        enabled: yes
