- name: Install and configure Nginx on Frontend
  hosts: frontend
  become: yes

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create Nginx proxy config for Netdata backend
      copy:
        dest: /etc/nginx/conf.d/netdata_proxy.conf
        content: |
          server {
              listen 80;
              
              location / {
                  proxy_pass http://{{ backend_ip }}:19999/;
                  proxy_http_version 1.1;
                  proxy_set_header Host $host;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
              }
          }

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
