- name: Install and configure Nginx on Frontend
  hosts: frontend
  become: yes
  vars:
    backend_server_ip: "{{ hostvars[groups['backend'][0]].ansible_default_ipv4.address }}"

  tasks:
    - name: Install Nginx on RedHat/Amazon Linux
      yum:
        name: nginx
        state: present
      when: ansible_os_family in ["RedHat", "Amazon"]

    - name: Install Nginx on Debian/Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Create Nginx proxy config for Netdata backend
      copy:
        dest: /etc/nginx/conf.d/netdata_proxy.conf
        content: |
          server {
              listen 80;

              location / {
                  proxy_pass http://{{ backend_server_ip }}:19999/;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                  proxy_set_header Host $host;
              }
          }

    - name: Restart Nginx to apply configuration
      service:
        name: nginx
        state: restarted
        enabled: yes
